apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: forearmed-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: forearmed-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forearmed-clusterrole
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.serviceAccountName }}"
    namespace: "{{ .Values.serviceAccountNamespace }}"
